services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      DEFAULT_USER_ROLE: pending
      ENABLE_LOGIN_FORM: true
      CUSTOM_NAME: Beazley Chat
      ENABLE_REALTIME_CHAT_SAVE: false
      ENABLE_CHANNELS: false
      AIOHTTP_CLIENT_TIMEOUT: 300
      ENABLE_OLLAMA_API: false
      ENABLE_AUTOCOMPLETE_GENERATION: false
      ENABLE_EVALUATION_ARENA_MODELS: false
      ENABLE_RAG_WEB_SEARCH: false
      ENABLE_IMAGE_GENERATION: false
      USER_PERMISSIONS_CHAT_FILE_UPLOAD: true
      USER_PERMISSIONS_CHAT_DELETE: true
      USER_PERMISSIONS_CHAT_EDIT: true
      USER_PERMISSIONS_CHAT_TEMPORARY: true
    restart: unless-stopped

volumes:
  open-webui: {}
